Repository world-famous-webserv/webserv, pull requests merged in 2023-12, with the labels that each got.

#30 Server, Client 생성자 수정
  libs/config/Makefile
  libs/config/block.cpp
  libs/config/block.hpp
  libs/config/conf.cpp
  libs/config/conf.hpp
  libs/config/config.cpp
  libs/config/config.hpp
  libs/config/simple.cpp
  libs/config/simple.hpp
  libs/config/utils.cpp
  libs/config/utils.hpp
  src/client.cpp
  src/client.hpp
  src/http/http.cpp
  src/http/http.hpp
  src/http/http_request.cpp
  src/main.cpp
  src/server.cpp
  src/server.hpp
  test/config/main.cpp
Labels: enhancement

#31 chore: fix build error
  libs/config/simple.cpp
  libs/config/simple.hpp
  src/http/http_request.hpp
  src/http/http_response.hpp
  src/server.cpp
Labels: chore

#32 Fix: slash로 끝나지 않는 location 찾지 못하는 문제, 폴더를 열었을 때 에러처리를 하지 못하는문제
  libs/config/block.cpp
  libs/config/conf.cpp
  libs/config/config.cpp
Labels: bug

#34 Fix: listen address default value change from "*" to "0.0.0.0"
  libs/config/simple.cpp
Labels: bug

#37 Feat: conf 정보 http의 member로 추가
  src/client.cpp
  src/client.hpp
  src/http/http.cpp
  src/http/http.hpp
  src/http/http_error.cpp
  src/server.hpp
Labels: chore, enhancement

#38 feat: method interface
  src/Makefile
  src/http/http.cpp
  src/http/http.hpp
  src/http/http_response.cpp
  src/http/method/get.cpp
Labels: enhancement

#39 index, autoindex 기능추가
  data/default.conf
  src/Makefile
  src/http/http.cpp
  src/http/http.hpp
  src/http/method/get.cpp
  src/http/method/index.cpp
  src/http/method/index.hpp
Labels: enhancement

#44 delete 기능추가
  src/Makefile
  src/http/http.cpp
  src/http/http.hpp
  src/http/method/delete.cpp
  src/http/method/delete.hpp
Labels: enhancement

#45 chunk message 요청 받기
  Makefile
  src/Makefile
  src/http/http.cpp
  src/http/http.hpp
  src/http/http_code.hpp
  src/http/http_request.cpp
  src/http/http_request.hpp
  src/http/method/delete.cpp
  src/http/method/get.cpp
  src/http/method/index.cpp
  src/http/method/post.cpp
Labels: enhancement

#48 CGI Interface
  Makefile
  data/default.conf
  data/juwon.conf
  data/juwon_template.conf
  libs/config/block.cpp
  libs/config/block.hpp
  libs/config/conf.cpp
  libs/multiplex/multiplex.cpp
  src/Makefile
  src/cgi/cgi.cpp
  src/cgi/cgi.hpp
  src/http/http.cpp
  src/http/http.hpp
  src/http/method/index.cpp
  src/http/method/post.cpp
  src/main.cpp
  www/cgi-bin/file_upload.py
  www/html/index.html
Labels: enhancement

#49 쿠키와 세션
  src/Makefile
  src/http/cookie.cpp
  src/http/cookie.hpp
  src/http/http_response.hpp
  src/http/session.cpp
  src/http/session.hpp
Labels: enhancement

#51 Fix: path error
  data/siege.conf
  libs/config/block.cpp
  libs/config/conf.cpp
Labels: bug

#53 #51 + location ubuntu_cgi_tester, root의 slash 제거
  data/siege.conf
  libs/config/block.cpp
  libs/config/conf.cpp
Labels: bug

#54 Feat: add fastcgi_pass, PATH_INFO
  data/siege.conf
  libs/config/block.cpp
  libs/config/block.hpp
  libs/config/conf.cpp
  libs/config/conf.hpp
  libs/config/simple.cpp
  libs/config/simple.hpp
  src/http/cgi.cpp
  src/http/cgi.hpp
  src/http/http.cpp
  src/http/method/get.cpp
Labels: enhancement

#55 Post: file upload and cgi process
  src/http/http.cpp
  src/http/http.hpp
  src/http/method/post.cpp
Labels: enhancement

#58 Cgi 수정
  data/siege.conf
  src/Makefile
  src/http/cgi.cpp
  src/http/cgi.hpp
  src/http/http.cpp
  src/http/http.hpp
  src/http/method/delete.cpp
  src/http/method/get.cpp
  src/http/method/post.cpp
  src/http/method/put.cpp
Labels: bug, enhancement

#60 Cgi_pass를 항상 절대경로로 받아야 함 && Cgi waitpid는 pid 값이 -1일 때만 하기
  libs/config/block.cpp
  libs/config/simple.cpp
  src/http/cgi.cpp
Labels: enhancement

#62 Feat: www directory add
  www/cgi-bin/file_upload.py
  www/html/index.html
Labels: enhancement

#63 Feat: cgi php calculator and python file uploader
  Makefile
  data/default.conf
  data/default_template.conf
  src/http/cgi.cpp
  src/http/http_request.cpp
  www/cgi-bin/calculate.php
  www/cgi-bin/file_upload.py
  www/html/calculate.html
  www/html/file_upload.html
  www/html/index.html
  www/uploaded_files/temp
Labels: enhancement

#64 new cgi
  Makefile
  data/default_template.conf
  src/http/cgi.cpp
  src/http/http_request.cpp
  www/cgi-bin/calculate.php
  www/cgi-bin/echo.sh
  www/cgi-bin/file_upload.py
  www/cgi-bin/myfiles.py
  www/html/calculate.html
  www/html/echo.html
  www/uploaded_files/temp
Labels: enhancement

#65 Conf 구조 수정
  libs/config/conf.cpp
  libs/config/conf.hpp
  www/css/error.css
  www/html/403.html
  www/html/404.html
  www/html/405.html
Labels: bug

#66 fix: python interal server error
  www/cgi-bin/file_upload.py
Labels: bug
